export const FLT_RESULTS_REQ_KEY = 'FLT_RESULTS_REQ_KEY';
export const SHOW_RETURN_FLTS = 'SHOW_RETURN_FLIGHTS';
export const SELECTED_DEP_FLT = 'SELECTED_DEP_FLT';
export const SELECTED_RETURN_FLT = 'SELECTED_RETURN_FLT';
